I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 33, in script call
    call question1
  File "game/script.rpy", line 80, in script call
    call correct
  File "game/script.rpy", line 45, in script
    $ correct += 1
  File "game/script.rpy", line 45, in <module>
    $ correct += 1
NameError: name 'correct' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 33, in script call
    call question1
  File "game/script.rpy", line 80, in script call
    call correct
  File "game/script.rpy", line 45, in script
    $ correct += 1
  File "C:\Users\Ojo\Downloads\renpy-8.0.0-sdk\renpy\ast.py", line 1111, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Ojo\Downloads\renpy-8.0.0-sdk\renpy\python.py", line 1049, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 45, in <module>
    $ correct += 1
NameError: name 'correct' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.0.22062402
MCAT Prep Game 1.0
Thu Aug 18 23:50:38 2022
